const data = {
  students: [
    {
      id: 1,
      name: "R.Sai Praveen",
      package: "13 LPA",
      company: "Wipro",
      department: "CSE",
      year: 2020,
    },
    {
      id: 2,
      name: "P. Surya",
      package: "11 LPA",
      company: "Infosys",
      department: "CSE",
      year: 2019,
    },
    {
      id: 3,
      name: "P. Prakash",
      package: "15 LPA",
      company: "Infosys",
      department: "EEE",
      year: 2019,
    },
    {
      id: 4,
      name: "A. K. Verma",
      package: "10 LPA",
      company: "Wipro",
      department: "ECE",
      year: 2020,
    },
    {
      id: 5,
      name: "M. V. Kumar",
      package: "3 LPA",
      company: "IBM",
      department: "Mechanical",
      year: 2020,
    },
    {
      id: 6,
      name: "S. Sajid",
      package: "12 LPA",
      company: "Infosys",
      department: "Civil",
      year: 2019,
    },
    {
      id: 7,
      name: "S. M. Mishra",
      package: "11.5 LPA",
      company: "Cognizant",
      department: "CSE",
      year: 2019,
    },
    {
      id: 8,
      name: "A. R. Singh",
      package: "10.5 LPA",
      company: "Tech Mahindra",
      department: "EEE",
      year: 2022,
    },
    {
      id: 9,
      name: "V. S. Sharma",
      package: "12.5 LPA",
      company: "Infosys",
      department: "ECE",
      year: 2022,
    },
    {
      id: 10,
      name: "P. P. Patel",
      package: "11 LPA",
      company: "Cognizant",
      department: "Mechanical",
      year: 2020,
    },
    {
      id: 11,
      name: "K. K. Kumar",
      package: "11.5 LPA",
      company: "Infosys",
      department: "Civil",
      year: 2021,
    },
    {
      id: 12,
      name: "Aditya Sharma",
      package: "10 LPA",
      company: "Infosys",
      department: "CSE",
      year: 2019,
    },
    {
      id: 13,
      name: "Neha Reddy",
      package: "8 LPA",
      company: "Infosys",
      department: "EEE",
      year: 2019,
    },
    {
      id: 14,
      name: "Rajesh Kumar",
      package: "9 LPA",
      company: "Wipro",
      department: "ECE",
      year: 2021,
    },
    {
      id: 15,
      name: "Amit Verma",
      package: "4 LPA",
      company: "Infosys",
      department: "Mechanical",
      year: 2021,
    },
    {
      id: 16,
      name: "Pooja Gupta",
      package: "3 LPA",
      company: "IBM",
      department: "Civil",
      year: 2021,
    },
    {
      id: 17,
      name: "Sandeep Mishra",
      package: "10.5 LPA",
      company: "Capgemini",
      department: "CSE",
      year: 2021,
    },
    {
      id: 18,
      name: "Anjali Singh",
      package: "9.5 LPA",
      company: "Tech Mahindra",
      department: "EEE",
      year: 2022,
    },
    {
      id: 19,
      name: "Vivek Sharma",
      package: "11.5 LPA",
      company: "Infosys",
      department: "ECE",
      year: 2022,
    },
    {
      id: 20,
      name: "Priya Patel",
      package: "10 LPA",
      company: "Cognizant",
      department: "Mechanical",
      year: 2021,
    },
    {
      id: 21,
      name: "Kiran Kumar",
      package: "10.5 LPA",
      company: "Infosys",
      department: "Civil",
      year: 2021,
    },
    {
      id: 22,
      name: "R. K. Singh",
      package: "12 LPA",
      company: "Infosys",
      department: "CSE",
      year: 2019,
    },
    {
      id: 23,
      name: "N. R. Reddy",
      package: "10 LPA",
      company: "Infosys",
      department: "EEE",
      year: 2019,
    },
    {
      id: 24,
      name: "S. K. Verma",
      package: "5 LPA",
      company: "Wipro",
      department: "ECE",
      year: 2021,
    },
    {
      id: 25,
      name: "M. A. Kumar",
      package: "6 LPA",
      company: "Tech Mahindra",
      department: "Mechanical",
      year: 2021,
    },
    {
      id: 26,
      name: "R. P. Gupta",
      package: "5 LPA",
      company: "Wipro",
      department: "Civil",
      year: 2021,
    },
    {
      id: 27,
      name: "S. S. Mishra",
      package: "12.5 LPA",
      company: "Capgemini",
      department: "CSE",
      year: 2021,
    },
    {
      id: 28,
      name: "A. K. Singh",
      package: "11.5 LPA",
      company: "Tech Mahindra",
      department: "EEE",
      year: 2022,
    },
    {
      id: 29,
      name: "V. K. Sharma",
      package: "13 LPA",
      company: "Infosys",
      department: "ECE",
      year: 2022,
    },
    {
      id: 30,
      name: "P. K. Patel",
      package: "11 LPA",
      company: "Cognizant",
      department: "Mechanical",
      year: 2021,
    },
    {
      id: 31,
      name: "K. R. Kumar",
      package: "11.5 LPA",
      company: "Infosys",
      department: "Civil",
      year: 2021,
    },
    {
      id: 32,
      name: "Ananya",
      package: "11 LPA",
      company: "Infosys",
      department: "CSE",
      year: 2019,
    },
    {
      id: 33,
      name: "Ganesh",
      package: "9 LPA",
      company: "Infosys",
      department: "EEE",
      year: 2019,
    },
    {
      id: 34,
      name: "Lakshmi",
      package: "10 LPA",
      company: "Wipro",
      department: "ECE",
      year: 2021,
    },
    {
      id: 35,
      name: "Prakash",
      package: "13 LPA",
      company: "Cognizant",
      department: "Mechanical",
      year: 2021,
    },
    {
      id: 36,
      name: "Sangeetha",
      package: "4 LPA",
      company: "IBM",
      department: "Civil",
      year: 2021,
    },
    {
      id: 37,
      name: "Ravi",
      package: "11.5 LPA",
      company: "Capgemini",
      department: "CSE",
      year: 2021,
    },
    {
      id: 38,
      name: "Sudha",
      package: "10.5 LPA",
      company: "Tech Mahindra",
      department: "EEE",
      year: 2022,
    },
    {
      id: 39,
      name: "Krishna",
      package: "12.5 LPA",
      company: "Infosys",
      department: "ECE",
      year: 2022,
    },
    {
      id: 40,
      name: "Ramesh",
      package: "11 LPA",
      company: "Cognizant",
      department: "Mechanical",
      year: 2021,
    },
    {
      id: 41,
      name: "Amit Sharma",
      package: "4 LPA",
      company: "IBM",
      department: "CSE",
      year: 2019,
    },
    {
      id: 42,
      name: "Nisha Verma",
      package: "4.5 LPA",
      company: "Wipro",
      department: "EEE",
      year: 2019,
    },
    {
      id: 43,
      name: "Rajesh Singh",
      package: "5 LPA",
      company: "Cognizant",
      department: "ECE",
      year: 2021,
    },
    {
      id: 44,
      name: "Anjali Reddy",
      package: "5.5 LPA",
      company: "Tech Mahindra",
      department: "Mechanical",
      year: 2021,
    },
    {
      id: 45,
      name: "Vikram Kumar",
      package: "6 LPA",
      company: "Infosys",
      department: "Civil",
      year: 2021,
    },
    {
      id: 46,
      name: "Priya Verma",
      package: "4 LPA",
      company: "Capgemini",
      department: "CSE",
      year: 2021,
    },
    {
      id: 47,
      name: "Kiran Singh",
      package: "4.5 LPA",
      company: "HCL Technologies",
      department: "EEE",
      year: 2022,
    },
    {
      id: 48,
      name: "Ramesh Verma",
      package: "5 LPA",
      company: "Infosys",
      department: "ECE",
      year: 2022,
    },
    {
      id: 49,
      name: "Aditi Singh",
      package: "5.5 LPA",
      company: "Infosys",
      department: "Mechanical",
      year: 2021,
    },
    {
      id: 50,
      name: "Neha Kumar",
      package: "6 LPA",
      company: "IBM",
      department: "Civil",
      year: 2021,
    },
    {
      id: 51,
      name: "Rakesh Sharma",
      package: "10 LPA",
      company: "Cognizant",
      department: "CSE",
      year: 2019,
    },
    {
      id: 52,
      name: "Sneha Reddy",
      package: "4.5 LPA",
      company: "Tech Mahindra",
      department: "EEE",
      year: 2019,
    },
    {
      id: 53,
      name: "Karthik Verma",
      package: "5 LPA",
      company: "Infosys",
      department: "ECE",
      year: 2020,
    },
    {
      id: 54,
      name: "Anusha Kumar",
      package: "5.5 LPA",
      company: "Tech Mahindra",
      department: "Mechanical",
      year: 2020,
    },
    {
      id: 55,
      name: "Vijay Verma",
      package: "6 LPA",
      company: "Wipro",
      department: "Civil",
      year: 2019,
    },
    {
      id: 56,
      name: "Divya Sharma",
      package: "4 LPA",
      company: "Capgemini",
      department: "CSE",
      year: 2019,
    },
    {
      id: 57,
      name: "Gopal Verma",
      package: "4.5 LPA",
      company: "Wipro",
      department: "EEE",
      year: 2022,
    },
    {
      id: 58,
      name: "Manju Kumar",
      package: "5 LPA",
      company: "Infosys",
      department: "ECE",
      year: 2022,
    },
    {
      id: 59,
      name: "Rajesh Verma",
      package: "5.5 LPA",
      company: "Tech Mahindra",
      department: "Mechanical",
      year: 2020,
    },
    {
      id: 60,
      name: "Ananya Sharma",
      package: "6 LPA",
      company: "Tata Consultancy Services",
      department: "Civil",
      year: 2020,
    },
    {
      id: 61,
      name: "Aditya Verma",
      package: "4 LPA",
      company: "Capgemini",
      department: "CSE",
      year: 2019,
    },
    {
      id: 62,
      name: "Neha Sharma",
      package: "4.5 LPA",
      company: "Wipro",
      department: "EEE",
      year: 2019,
    },
    {
      id: 63,
      name: "Rajesh Verma",
      package: "5 LPA",
      company: "Tech Mahindra",
      department: "ECE",
      year: 2020,
    },
    {
      id: 64,
      name: "Anjali Singh",
      package: "5.5 LPA",
      company: "Tata Consultancy Services",
      department: "Mechanical",
      year: 2020,
    },
    {
      id: 65,
      name: "Vivek Kumar",
      package: "6 LPA",
      company: "HCL Technologies",
      department: "Civil",
      year: 2019,
    },
    {
      id: 66,
      name: "Priya Verma",
      package: "4 LPA",
      company: "Infosys",
      department: "CSE",
      year: 2019,
    },
    {
      id: 67,
      name: "Kiran Sharma",
      package: "4.5 LPA",
      company: "Tata Consultancy Services",
      department: "EEE",
      year: 2022,
    },
    {
      id: 68,
      name: "Ramesh Kumar",
      package: "5 LPA",
      company: "Tech Mahindra",
      department: "ECE",
      year: 2022,
    },
    {
      id: 69,
      name: "Aditi Verma",
      package: "5.5 LPA",
      company: "Wipro",
      department: "Mechanical",
      year: 2020,
    },
    {
      id: 70,
      name: "Nisha Singh",
      package: "6 LPA",
      company: "Infosys",
      department: "Civil",
      year: 2020,
    }, 
    {
      id: 71,
      name: "S. K. Singh",
      package: "11 LPA",
      company: "Tata Consultancy Services",
      department: "CSE",
      year: 2019,
    },
    {
      id: 72,
      name: "R. N. Reddy",
      package: "9 LPA",
      company: "Infosys",
      department: "EEE",
      year: 2019,
    },
    {
      id: 73,
      name: "P. S. Gupta",
      package: "12 LPA",
      company: "Larsen & Toubro",
      department: "Civil",
      year: 2019,
    },
    {
      id: 74,
      name: "R. S. Verma",
      package: "4.5 LPA",
      company: "Infosys",
      department: "CSE",
      year: 2022,
    },
    {
      id: 75,
      name: "S. K. Sharma",
      package: "4 LPA",
      company: "Tech Mahindra",
      department: "ECE",
      year: 2022,
    },
    {
      id: 76,
      name: "V. K. Kumar",
      package: "4.2 LPA",
      company: "Wipro",
      department: "CSE",
      year: 2020,
    },
    {
      id: 77,
      name: "P. R. Singh",
      package: "4.8 LPA",
      company: "Infosys",
      department: "CSE",
      year: 2020,
    },
    {
      id: 78,
      name: "M. V. Verma",
      package: "4.3 LPA",
      company: "Tech Mahindra",
      department: "ECE",
      year: 2019,
    },
    {
      id: 79,
      name: "R. N. Kumar",
      package: "4.7 LPA",
      company: "Wipro",
      department: "CSE",
      year: 2019,
    },
    {
      id: 80,
      name: "A. K. Gupta",
      package: "4.2 LPA",
      company: "Infosys",
      department: "ECE",
      year: 2020,
    },
    {
      id: 81,
      name: "S. S. Singh",
      package: "4.5 LPA",
      company: "Tech Mahindra",
      department: "ECE",
      year: 2020,
    },
    {
      id: 82,
      name: "V. P. Verma",
      package: "4.6 LPA",
      company: "Wipro",
      department: "CSE",
      year: 2019,
    },
    {
      id: 83,
      name: "P. S. Kumar",
      package: "4.3 LPA",
      company: "Infosys",
      department: "CSE",
      year: 2019,
    },
  ],
};

export default data;
