const express=require('express');
const { getClubs } = require('../controllers/clubControllers');
const isAuth=require('../middleware/auth');
const { getClubevents, getRegisterusers, getClubregistrations,  eventRegistration, deleteUserregister,updateWinner,updateRunner } = require('../controllers/eventControllers');
const router=express.Router();
router.get('/all',getClubevents);
router.get('/register/all',isAuth,getClubregistrations);
router.patch('/register/update/winner/:roll',isAuth,updateWinner);
router.patch('/register/update/runner/:roll',isAuth,updateRunner);
router.post('/register',isAuth,eventRegistration);
router.delete('/registration/delete/:rollno',isAuth,deleteUserregister);
module.exports=router;